# project.py

NAME = "nads-server"
DESCRIPTION = "nAds - A simple app to detect ads on TV channels"
VERSION = "0.0.1"

# this file is auto-generated by the envconfig.local script - do not edit this file manually.
